version: '3'

services:
  web:
    build: ./src
    image: django-project:latest
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-project
    volumes:
      - ./src:/src
    ports:
        - "8000:8000"

