version: '3'

services:
  web:
    image: django-project:latest
    command: bash -c "cd /src && python manage.py runserver 0.0.0.0:8000"
    container_name: django-project
    ports:
        - "8000:8000"

