FROM python:3.8

ARG appname=app

COPY requirements.txt /tmp
RUN python3.8 -m pip install -r /tmp/requirements.txt

ENV PYTHONUNBUFFERED 1

RUN django-admin startproject server
RUN mv server src

WORKDIR src
RUN python manage.py startapp ${appname}

WORKDIR ${appname}
RUN printf "from rest_framework import serializers" > serializers.py

RUN printf "from django.urls import path\n\
from . import views\n\n\
app_name = '${appname}'\n\n\
urlpatterns = []" >  urls.py

WORKDIR /src

RUN sed -i "/import path/ s/$/, include/" server/urls.py
RUN sed -i "/import path, include/ a from drf_yasg.views import get_schema_view" server/urls.py
RUN sed -i "/import get_schema_view/ a from drf_yasg import openapi" server/urls.py

RUN sed -i "/import openapi/ a schema_view = get_schema_view(openapi.Info(" server/urls.py
RUN sed -i "/openapi.Info(/ a \ \ \ \ title='API'," server/urls.py
RUN sed -i "/title='API',/ a \ \ \ \ default_version='v1'))" server/urls.py

RUN echo "urlpatterns += [path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='api_docs')]" >> server/urls.py
